# -*- coding: utf-8 -*-
"""SelectionSort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KkQ6RUyYrVaoisNswvIsg253r8hLjQeR
"""

def search_smaller(l):
  smaller = l[0]
  smaller_idx = 0
  for idx, element in enumerate(l):
    if element < smaller:
      smaller = element
      smaller_idx = idx
  return smaller_idx

search_smaller([10, 0, 5, 8, 11])

def selection_sort(l):
    new_l = []
    for i in range (len(l)):
      smaller_one = search_smaller(l)
      new_l.append(l.pop(smaller_one))
    return new_l, l

selection_sort([5, 10, 3, 32, 88 ])

l = [5, 10, 3, 32, 88 ]

l.sort()
l

def selection_sort_2(l):
  n = len(l)

  for i in range(n):
    smaller_idx = i

    for j in range(i+1, n):
      if l[j] < l[smaller_idx]:
        smaller_idx = j

    l[i], l[smaller_idx] = l[smaller_idx], l[i]

  return l

selection_sort_2([5, 10, 3, 32, 88])